#! /usr/bin/env bash

# TODO: Make it work.

infile=$1
machine_file=${infile}.m
curl=curl
which $curl &> /dev/null
if [ $? != 0 ]; then
    echo "No $curl."
    exit 1
fi

./compile $infile 
if [ $? != 0 ]; then
    echo "Translation to machine code failed."
    exit 1
fi
$curl -F 'action=assemblera' -F 'out=binary' -F "code=@$machine_file" ass.sjlander.com
