#! /usr/bin/env bash

infile=$1
curl=curl
which $curl &> /dev/null
if [ $? != 0 ]; then
    echo "No $curl."
    exit 1
fi

./compile $infile 
if [ $? != 0 ]; then
    echo "Translation to machine code failed."
    exit 1
fi
$curl -F 'action=assemblera' -F 'out=binary' -F "code=@$infile" ass.sjlander.com
